exclude: '^(.*egg.info.*|.*/parameters.py).*$'
repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.15.0
    hooks:
        -   id: pyupgrade
-   repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        exclude: ^docs/
        args: ["--multi-line", "3",
               "--trailing-comma",
               "--force-grid-wrap", "0",
               "--use-parentheses",
               "--ensure-newline-before-comments",
               "--line-length", "88",
               "--combine-as",
               "--project", "snowflake.connector",
               "--project", "snowflake.snowpark",
        ]
-   repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        exclude: ^docs/
        args:
          - --safe
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: >
            (?x)^(
                license_header.txt|
                tests/resources/.*|
                docs/.*|
            )$
    -   id: check-yaml
        # The first two lines of meta.yaml does not work with check-yaml
        exclude: recipe/meta.yaml
    -   id: debug-statements
    -   id: check-ast
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.1.10
    hooks:
    -   id: insert-license
        name: insert-py-license
        files: >
            (?x)^(
                src/snowflake/snowpark/.*\.py|
                tests/.*\.py|
            )$
        exclude: >
            (?x)^(
                src/snowflake/snowpark/version.py|
                tests/resources/.*\.py|
            )$
        args:
            - --license-filepath
            - license_header.txt
# TODO: SNOW-370289 Reformat the codebase to pass flake8 precommit hook
#-   repo: https://gitlab.com/pycqa/flake8
#    rev: 3.9.2
#    hooks:
#      - id: flake8
#        additional_dependencies:
#          - flake8-bugbear == 20.11.1
#        args: ["--ignore", "B011,C901,D100,D101,D102,D103,D104,D105,D107,D401,E203,E402,E501,F821,W503",
#               "--exclude", "parameters.py, *venv*",
#               "--max-line-length", "88",
#               "--show-source"]
